# attogram/shared-media-orm - codeclimate.yml - v0.0.1
version: "2"
exclude_patterns:
- "vendor/"
- "config/"
- "src/Attogram/SharedMedia/Orm/Base/"
- "src/Attogram/SharedMedia/Orm/Map/"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  phan:
    enabled: true
    checks:
      PhanUndeclaredClassConstant:
        enabled: false
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUndeclaredMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
  duplication:
    enabled: true
  csslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
