# attogram/shared-media-orm - codeclimate.yml - v1.0.1
version: "2"
exclude_patterns:
- "vendor/"
- "config/"
- "src/Attogram/SharedMedia/Orm/Base/"
- "src/Attogram/SharedMedia/Orm/Map/"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess: # allow Object::method()
        enabled: false
      #Controversial/Superglobals: # allow $_GET in sandbox
      #  enabled: false
      Design/DevelopmentCodeFragment: # allow print_r()
        enabled: false
  phan:
    enabled: true
    checks:
      PhanTypeMismatchArgument:
        enabled: false
      PhanTypeMismatchProperty:
        enabled: false
      PhanUndeclaredClass:
        enabled: false
      PhanUndeclaredClassCatch:
        enabled: false
      PhanUndeclaredClassConstant:
        enabled: false
      PhanUndeclaredClassInstanceof:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUndeclaredInterface:
        enabled: false
      PhanUndeclaredMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
      PhanUndeclaredTypeParameter:
        enabled: false
  duplication:
    enabled: true
  csslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
